// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQF4oJBgyxa67rU9d0Jg5a1tPSF6N02Ts',
    appId: '1:773540972927:android:95b3834ba00a56939db24a',
    messagingSenderId: '773540972927',
    projectId: 'bespokepelle-17af7',
    storageBucket: 'bespokepelle-17af7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDceymNO1F3osJ7WzVdHFlv7eVupaESL58',
    appId: '1:773540972927:ios:882969020359eec39db24a',
    messagingSenderId: '773540972927',
    projectId: 'bespokepelle-17af7',
    storageBucket: 'bespokepelle-17af7.appspot.com',
    androidClientId: '773540972927-2icm2bbjfhu4to503ofcv4h9j9uklhbv.apps.googleusercontent.com',
    iosClientId: '773540972927-h1nnfmai7fkkcva8ek80orr6bpornstf.apps.googleusercontent.com',
    iosBundleId: 'com.example.assetracBespokepelle',
  );
}
